stages:
  clean_metadata:
    cmd: python3 src/clean_metadata.py
        --input_file datasets/meta_Electronics.json
        --output_file datasets/cleaned_data.json
    outs:
    - datasets/cleaned_data.json
  train_lda:
    cmd: python3 src/train_lda.py
        --input_file data/cleaned_output.csv
        --output_model models/lda_model.joblib
