stages:
  clean_metadata:
    cmd: python3 src/clean_metadata.py
        --input_file datasets/meta_Electronics.json
        --output_file datasets/cleaned_data.json
    outs:
    - datasets/cleaned_data.json
  generate_review_features:
    cmd: python3 src/generate_review_features.py
        --input_file datasets/Electronics_5.json
        --output_dataset_dir datasets/
    outs:
    - datasets/
  m1_preparation:
    cmd: python3 src/m1_preparation.py
        --input_file datasets/cleaned_data.json
        --input_file_category_string_index datasets/m1_data/category_string_index.pickle
        --output_dataset_dir datasets/m1_data/
        --output_index_dir index/
        --output_model_dir models/
    deps:
    - datasets/cleaned_data.json
    outs:
    - datasets/m1_data/
    - index/
    - models/
  m2_preparation:
    cmd: python3 src/m2_preparation.py
        --input_file datasets/cleaned_data.json
        --output_dataset_dir datasets/m2_data/
        --output_ranking_dataset_dir datasets/r1_data/
        --output_index_dir index/
        --output_model_dir models/
    deps:
    - datasets/cleaned_data.json
    outs:
    - datasets/m2_data/
    - datasets/r1_data/
    - index/
    - models/
  r1_preparation:
    cmd: python3 src/r1_preparation.py
        --input_file datasets/cleaned_data.json
        --input_ratings datasets/ratings.csv
        --output_dataset_dir datasets/r1_data/
        --output_model_dir models/
    deps:
    - datasets/cleaned_data.json
    - datasets/ratings.csv
    outs:
    - datasets/r1_data/
    - index/
    - models/
  r2_preparation:
    cmd: python3 src/r2_preparation.py
        --input_r1_dataset_dir datasets/r1_data/
        --input_r1_index index/R1_index_asin.pickle
        --input_review_sentiment_dir datasets/
        --output_r2_dir datasets/r2_data/
    deps:
    - datasets/
    - index/R1_index_asin.pickle
    outs:
    - datasets/r2_data/R2_Rank_mtx.npz
